services:
  - type: web
    name: smartschedule-g3
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: SESSION_SECRET
        value: smartschedule-secret-2026
      - key: PYTHON_VERSION
        value: 3.11.0
